import { resolve } from "path";
import { defineConfig } from "vite";
import InjectPreload from "unplugin-inject-preload/vite";

export default defineConfig({
  root: "app",
  plugins: [
    InjectPreload({
      files: [
        {
          // Match the hashed font file generated by Fontsource in your build
          outputMatch: /inter-latin-wght-normal.*\.woff2$/,
          attributes: {
            type: "font/woff2",
            as: "font",
            crossorigin: "anonymous",
          },
        },
      ],
    }),
  ],
  build: {
    outDir: "../dist",
    rollupOptions: {
      input: {
        main: resolve(__dirname, "app", "index.html"),
      },
    },
  },
});
